<a href="https://colab.research.google.com/github/BilalKhaliqWillis/BILAL-Assignment2/blob/main/BILAL_Assignment_5_Time_Series_Data_Manipulation_with_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
# Assignment5: Time Series Data Manipulation with pandas
# Uploading File in Google Colab (If Needed)

from google.colab import files
uploaded = files.upload()

Saving 2016-weather-data-seattle.csv to 2016-weather-data-seattle.csv

In [4]:
# Importing the Required Libraries
import pandas as pd
import numpy as np

# Displaying settings for better reading
pd.set_option('display.max_rows', 10)
pd.set_option('display.max_columns', None)

In [15]:
# Loading the Dataset
import pandas as pd

df = pd.read_csv("2016-weather-data-seattle.csv")

df.head()

       Date  Max_TemperatureC  Mean_TemperatureC  Min_TemperatureC
0  1/1/1948                10                8.0               7.0
1  1/2/1948                 6                4.0               3.0
2  1/3/1948                 7                4.0               2.0
3  1/4/1948                 7                4.0               2.0
4  1/5/1948                 7                3.0               0.0

In [23]:
# Clean column names
df.columns = df.columns.str.strip()

print("Columns:", df.columns)

# If Date column exists, we convert it
if 'Date' in df.columns:
    df['Date'] = pd.to_datetime(df['Date'])
    df.set_index('Date', inplace=True)
else:
    df.index = pd.to_datetime(df.index)

df.head()

Columns: Index(['Max_TemperatureC', 'Mean_TemperatureC', 'Min_TemperatureC'], dtype='object')

            Max_TemperatureC  Mean_TemperatureC  Min_TemperatureC
Date
1948-01-01                10                8.0               7.0
1948-01-02                 6                4.0               3.0
1948-01-03                 7                4.0               2.0
1948-01-04                 7                4.0               2.0
1948-01-05                 7                3.0               0.0

In [26]:
# Changing the Frequency from Daily to Weekly Using asfreq()
# Converting daily data to weekly frequency
# 'W' means weekly (Sunday by default)
weekly_df = df.asfreq('W')

# Applying forward fill (padding) to fill missing values
weekly_df = weekly_df.ffill()

# Displaying the result
weekly_df.head()

            Max_TemperatureC  Mean_TemperatureC  Min_TemperatureC
Date
1948-01-04               7.0                4.0               2.0
1948-01-11               5.0                3.0               1.0
1948-01-18               1.0                0.0              -1.0
1948-01-25               8.0                4.0               0.0
1948-02-01               4.0                2.0               0.0

In [28]:
# Extracting Time Components
# Extracting the time components from DatetimeIndex

df['Year'] = df.index.year
df['Month'] = df.index.month
df['Day'] = df.index.day
df['Day_of_Week'] = df.index.day_name()

# Displaying updated dataframe
df.head()

,Max_TemperatureC,Mean_TemperatureC,Min_TemperatureC,Year,Month,Day,Day_of_Week
Date,,,,,,,
1948-01-01,10,8.0,7.0,1948,1,1,Thursday
1948-01-02,6,4.0,3.0,1948,1,2,Friday
1948-01-03,7,4.0,2.0,1948,1,3,Saturday
1948-01-04,7,4.0,2.0,1948,1,4,Sunday
1948-01-05,7,3.0,0.0,1948,1,5,Monday

In [29]:
# Reindex to Include All Days of 2016
# Creating full date range for 2016
full_date_range = pd.date_range(start='2016-01-01',
                                end='2016-12-31',
                                freq='D')

# Reindexing dataframe
df_reindexed = df.reindex(full_date_range)

# Displaying missing values count
df_reindexed.isna().sum()

Max_TemperatureC     366
Mean_TemperatureC    366
Min_TemperatureC     366
Year                 366
Month                366
Day                  366
Day_of_Week          366
dtype: int64

In [30]:
# Truncating the Dataset to Specific Date Range
# Truncate dataset between Jan 1 and Jan 15, 2016
df_truncated = df.truncate(before='2016-01-01',
                           after='2016-01-15')

df_truncated

Empty DataFrame
Columns: [Max_TemperatureC, Mean_TemperatureC, Min_TemperatureC, Year, Month, Day, Day_of_Week]
Index: []