<a href="https://colab.research.google.com/github/BilalKhaliqWillis/BILAL-Assignment2/blob/main/BILAL_Assignment_6_Advanced_Time_Series_Data_Analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# Installing and Importing the Required Libraries
# Installing the required libraries
!pip install pandas matplotlib seaborn scikit-learn statsmodels

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: matplotlib in /usr/local/lib/python3.12/dist-packages (3.10.0)
Requirement already satisfied: seaborn in /usr/local/lib/python3.12/dist-packages (0.13.2)
Requirement already satisfied: scikit-learn in /usr/local/lib/python3.12/dist-packages (1.6.1)
Requirement already satisfied: statsmodels in /usr/local/lib/python3.12/dist-packages (0.14.6)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (4.61.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (1.4.9)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (26.0)
Requirement already satisfied: pillow>=8 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (11.3.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib) (3.3.2)
Requirement already satisfied: scipy>=1.6.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.16.3)
Requirement already satisfied: joblib>=1.2.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (1.5.3)
Requirement already satisfied: threadpoolctl>=3.1.0 in /usr/local/lib/python3.12/dist-packages (from scikit-learn) (3.6.0)
Requirement already satisfied: patsy>=0.5.6 in /usr/local/lib/python3.12/dist-packages (from statsmodels) (1.0.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [ ]:
import pandas as pd
import numpy as np

# Load dataset correctly
df = pd.read_csv("AirQualityUCI.csv", sep=';', decimal=',')

# Remove completely empty columns
df = df.dropna(axis=1, how='all')

df.head()

,Date,Time,CO(GT),PT08.S1(CO),NMHC(GT),C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),T,RH,AH
0,10/03/2004,18.00.00,2.6,1360.0,150.0,11.9,1046.0,166.0,1056.0,113.0,1692.0,1268.0,13.6,48.9,0.7578
1,10/03/2004,19.00.00,2.0,1292.0,112.0,9.4,955.0,103.0,1174.0,92.0,1559.0,972.0,13.3,47.7,0.7255
2,10/03/2004,20.00.00,2.2,1402.0,88.0,9.0,939.0,131.0,1140.0,114.0,1555.0,1074.0,11.9,54.0,0.7502
3,10/03/2004,21.00.00,2.2,1376.0,80.0,9.2,948.0,172.0,1092.0,122.0,1584.0,1203.0,11.0,60.0,0.7867
4,10/03/2004,22.00.00,1.6,1272.0,51.0,6.5,836.0,131.0,1205.0,116.0,1490.0,1110.0,11.2,59.6,0.7888

In [ ]:
# Combine Date and Time
df['Datetime'] = pd.to_datetime(df['Date'] + ' ' + df['Time'], errors='coerce')

# Remove rows where datetime failed
df = df.dropna(subset=['Datetime'])

# Set index
df = df.set_index('Datetime')

# Sort index
df = df.sort_index()

df.head()

/tmp/ipykernel_164/3589050872.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Datetime'] = pd.to_datetime(df['Date'] + ' ' + df['Time'], errors='coerce')

Empty DataFrame
Columns: [Date, Time, CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH]
Index: []

In [ ]:
# Convert CO(GT) to Numeric and Handle Missing Values
# Convert to numeric
df['CO(GT)'] = pd.to_numeric(df['CO(GT)'], errors='coerce')

# Replace missing placeholder
df['CO(GT)'] = df['CO(GT)'].replace(-200, np.nan)

# Interpolate missing values
df['CO(GT)'] = df['CO(GT)'].interpolate(method='time')

df['CO(GT)'].head()

Series([], Name: CO(GT), dtype: float64)

In [ ]:
# Create Daily Series
co_series = df['CO(GT)'].resample('D').mean().dropna()

print("Number of observations:", len(co_series))

co_series.head()

Number of observations: 0

Series([], Freq: D, Name: CO(GT), dtype: float64)

In [ ]:
# Uploading and Loading the Dataset
# Upload dataset from local machine
from google.colab import files
uploaded = files.upload()

Saving AirQualityUCI.csv to AirQualityUCI (1).csv

In [ ]:
df = pd.read_csv("AirQualityUCI.csv", sep=';', decimal=',')

# Remove empty columns
df = df.dropna(axis=1, how='all')

df.head()

,Date,Time,CO(GT),PT08.S1(CO),NMHC(GT),C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),T,RH,AH
0,10/03/2004,18.00.00,2.6,1360.0,150.0,11.9,1046.0,166.0,1056.0,113.0,1692.0,1268.0,13.6,48.9,0.7578
1,10/03/2004,19.00.00,2.0,1292.0,112.0,9.4,955.0,103.0,1174.0,92.0,1559.0,972.0,13.3,47.7,0.7255
2,10/03/2004,20.00.00,2.2,1402.0,88.0,9.0,939.0,131.0,1140.0,114.0,1555.0,1074.0,11.9,54.0,0.7502
3,10/03/2004,21.00.00,2.2,1376.0,80.0,9.2,948.0,172.0,1092.0,122.0,1584.0,1203.0,11.0,60.0,0.7867
4,10/03/2004,22.00.00,1.6,1272.0,51.0,6.5,836.0,131.0,1205.0,116.0,1490.0,1110.0,11.2,59.6,0.7888

In [ ]:
# Basic information about dataset
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9471 entries, 0 to 9470
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Date           9357 non-null   object
 1   Time           9357 non-null   object
 2   CO(GT)         9357 non-null   float64
 3   PT08.S1(CO)    9357 non-null   float64
 4   NMHC(GT)       9357 non-null   float64
 5   C6H6(GT)       9357 non-null   float64
 6   PT08.S2(NMHC)  9357 non-null   float64
 7   NOx(GT)        9357 non-null   float64
 8   PT08.S3(NOx)   9357 non-null   float64
 9   NO2(GT)        9357 non-null   float64
 10  PT08.S4(NO2)   9357 non-null   float64
 11  PT08.S5(O3)    9357 non-null   float64
 12  T              9357 non-null   float64
 13  RH             9357 non-null   float64
 14  AH             9357 non-null   float64
dtypes: float64(13), object(2)
memory usage: 1.1+ MB

In [ ]:
# Summary Stats
df.describe()

,CO(GT),PT08.S1(CO),NMHC(GT),C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),T,RH,AH
count,9357.000000,9357.000000,9357.000000,9357.000000,9357.000000,9357.000000,9357.000000,9357.000000,9357.000000,9357.000000,9357.000000,9357.000000,9357.000000
mean,-34.207524,1048.990061,-159.090093,1.865683,894.595276,168.616971,794.990168,58.148873,1391.479641,975.072032,9.778305,39.485380,-6.837604
std,77.657170,329.832710,139.789093,41.380206,342.333252,257.433866,321.993552,126.940455,467.210125,456.938184,43.203623,51.216145,38.976670
min,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000
25%,0.600000,921.000000,-200.000000,4.000000,711.000000,50.000000,637.000000,53.000000,1185.000000,700.000000,10.900000,34.100000,0.692300
50%,1.500000,1053.000000,-200.000000,7.900000,895.000000,141.000000,794.000000,96.000000,1446.000000,942.000000,17.200000,48.600000,0.976800
75%,2.600000,1221.000000,-200.000000,13.600000,1105.000000,284.000000,960.000000,133.000000,1662.000000,1255.000000,24.100000,61.900000,1.296200
max,11.900000,2040.000000,1189.000000,63.700000,2214.000000,1479.000000,2683.000000,340.000000,2775.000000,2523.000000,44.600000,88.700000,2.231000

In [ ]:
# Combine Date and Time into one datetime column
df['Datetime'] = pd.to_datetime(df['Date'] + ' ' + df['Time'], errors='coerce')

# Remove rows where datetime could not be created
df = df.dropna(subset=['Datetime'])

# Set datetime as index
df.set_index('Datetime', inplace=True)

# Sort by time
df = df.sort_index()

df.head()

/tmp/ipykernel_164/816045048.py:2: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Datetime'] = pd.to_datetime(df['Date'] + ' ' + df['Time'], errors='coerce')

Empty DataFrame
Columns: [Date, Time, CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH]
Index: []

In [ ]:
# Select Relevant Columns
selected_cols = ['CO(GT)', 'NOx(GT)', 'T', 'RH']

df[selected_cols].head()

Empty DataFrame
Columns: [CO(GT), NOx(GT), T, RH]
Index: []

In [ ]:
# Replace Missing Values (-200 → NaN)
# Replace placeholder values with NaN
df[selected_cols] = df[selected_cols].replace(-200, np.nan)

# Check missing values
df[selected_cols].isna().sum()

CO(GT)     0
NOx(GT)    0
T          0
RH         0
dtype: int64

In [ ]:
# Handle Missing Values

""" Strategy:

Interpolation for pollutant data

Mean fill for weather data """

# Interpolate pollutant data
df['CO(GT)'] = df['CO(GT)'].interpolate(method='time')
df['NOx(GT)'] = df['NOx(GT)'].interpolate(method='time')

# Fill weather data with mean
df['T'] = df['T'].fillna(df['T'].mean())
df['RH'] = df['RH'].fillna(df['RH'].mean())

# Verify again
df[selected_cols].isna().sum()

CO(GT)     0
NOx(GT)    0
T          0
RH         0
dtype: int64

In [ ]:
# Descriptive Statistics
df[selected_cols].describe()

       CO(GT)  NOx(GT)    T   RH
count     0.0      0.0  0.0  0.0
mean      NaN      NaN  NaN  NaN
std       NaN      NaN  NaN  NaN
min       NaN      NaN  NaN  NaN
25%       NaN      NaN  NaN  NaN
50%       NaN      NaN  NaN  NaN
75%       NaN      NaN  NaN  NaN
max       NaN      NaN  NaN  NaN

In [ ]:
# Check Data Types
df[selected_cols].dtypes

CO(GT)     float64
NOx(GT)    float64
T          float64
RH         float64
dtype: object

In [ ]:
# Converting it if necessary:-
df[selected_cols] = df[selected_cols].astype(float)

In [ ]:
# Ensure CO(GT) is numeric
df['CO(GT)'] = pd.to_numeric(df['CO(GT)'], errors='coerce')

# Replace placeholder missing values
df['CO(GT)'] = df['CO(GT)'].replace(-200, np.nan)

# Fill missing values using time interpolation
df['CO(GT)'] = df['CO(GT)'].interpolate(method='time')

# Create daily time series
co_series = df['CO(GT)'].resample('D').mean()

# Remove remaining missing values
co_series = co_series.dropna()

print("Number of observations:", len(co_series))
co_series.head()

Number of observations: 0

Series([], Freq: D, Name: CO(GT), dtype: float64)

In [ ]:
from statsmodels.tsa.seasonal import seasonal_decompose

decomposition = seasonal_decompose(co_series, model='additive', period=7)

ValueError: x must have 2 complete cycles requires 14 observations. x only has 0 observation(s)

In [ ]:
# Initial Exploration
# Dataset information
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9471 entries, 0 to 9470
Data columns (total 15 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Date           9357 non-null   object
 1   Time           9357 non-null   object
 2   CO(GT)         9357 non-null   float64
 3   PT08.S1(CO)    9357 non-null   float64
 4   NMHC(GT)       9357 non-null   float64
 5   C6H6(GT)       9357 non-null   float64
 6   PT08.S2(NMHC)  9357 non-null   float64
 7   NOx(GT)        9357 non-null   float64
 8   PT08.S3(NOx)   9357 non-null   float64
 9   NO2(GT)        9357 non-null   float64
 10  PT08.S4(NO2)   9357 non-null   float64
 11  PT08.S5(O3)    9357 non-null   float64
 12  T              9357 non-null   float64
 13  RH             9357 non-null   float64
 14  AH             9357 non-null   float64
dtypes: float64(13), object(2)
memory usage: 1.1+ MB

In [ ]:
# Summary statistics
df.describe()

,CO(GT),PT08.S1(CO),NMHC(GT),C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),T,RH,AH,Unnamed: 15,Unnamed: 16
count,9357.000000,9357.000000,9357.000000,9357.000000,9357.000000,9357.000000,9357.000000,9357.000000,9357.000000,9357.000000,9357.000000,9357.000000,9357.000000,0.0,0.0
mean,-34.207524,1048.990061,-159.090093,1.865683,894.595276,168.616971,794.990168,58.148873,1391.479641,975.072032,9.778305,39.485380,-6.837604,NaN,NaN
std,77.657170,329.832710,139.789093,41.380206,342.333252,257.433866,321.993552,126.940455,467.210125,456.938184,43.203623,51.216145,38.976670,NaN,NaN
min,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,NaN,NaN
25%,0.600000,921.000000,-200.000000,4.000000,711.000000,50.000000,637.000000,53.000000,1185.000000,700.000000,10.900000,34.100000,0.692300,NaN,NaN
50%,1.500000,1053.000000,-200.000000,7.900000,895.000000,141.000000,794.000000,96.000000,1446.000000,942.000000,17.200000,48.600000,0.976800,NaN,NaN
75%,2.600000,1221.000000,-200.000000,13.600000,1105.000000,284.000000,960.000000,133.000000,1662.000000,1255.000000,24.100000,61.900000,1.296200,NaN,NaN
max,11.900000,2040.000000,1189.000000,63.700000,2214.000000,1479.000000,2683.000000,340.000000,2775.000000,2523.000000,44.600000,88.700000,2.231000,NaN,NaN

In [ ]:
# Checking column names
df.columns

Index(['Date', 'Time', 'CO(GT)', 'PT08.S1(CO)', 'NMHC(GT)', 'C6H6(GT)',
       'PT08.S2(NMHC)', 'NOx(GT)', 'PT08.S3(NOx)', 'NO2(GT)', 'PT08.S4(NO2)',
       'PT08.S5(O3)', 'T', 'RH', 'AH', 'Unnamed: 15', 'Unnamed: 16'],
      dtype='object')

In [ ]:
# Creating the Datetime Index
# The dataset has separate Date and Time columns
# Combining the Date and Time into a single datetime column
df['Datetime'] = pd.to_datetime(df['Date'] + ' ' + df['Time'], errors='coerce')

# Setting as index
df.set_index('Datetime', inplace=True)

df.head()

/tmp/ipykernel_164/3221282097.py:4: UserWarning: Could not infer format, so each element will be parsed individually, falling back to `dateutil`. To ensure parsing is consistent and as-expected, please specify a format.
  df['Datetime'] = pd.to_datetime(df['Date'] + ' ' + df['Time'], errors='coerce')

,Date,Time,CO(GT),PT08.S1(CO),NMHC(GT),C6H6(GT),PT08.S2(NMHC),NOx(GT),PT08.S3(NOx),NO2(GT),PT08.S4(NO2),PT08.S5(O3),T,RH,AH,Unnamed: 15,Unnamed: 16
Datetime,,,,,,,,,,,,,,,,,
NaT,10/03/2004,18.00.00,2.6,1360.0,150.0,11.9,1046.0,166.0,1056.0,113.0,1692.0,1268.0,13.6,48.9,0.7578,NaN,NaN
NaT,10/03/2004,19.00.00,2.0,1292.0,112.0,9.4,955.0,103.0,1174.0,92.0,1559.0,972.0,13.3,47.7,0.7255,NaN,NaN
NaT,10/03/2004,20.00.00,2.2,1402.0,88.0,9.0,939.0,131.0,1140.0,114.0,1555.0,1074.0,11.9,54.0,0.7502,NaN,NaN
NaT,10/03/2004,21.00.00,2.2,1376.0,80.0,9.2,948.0,172.0,1092.0,122.0,1584.0,1203.0,11.0,60.0,0.7867,NaN,NaN
NaT,10/03/2004,22.00.00,1.6,1272.0,51.0,6.5,836.0,131.0,1205.0,116.0,1490.0,1110.0,11.2,59.6,0.7888,NaN,NaN

In [ ]:
# Identify Relevant Columns for Time Series
"""We will be using the : -

CO(GT)

NOx(GT)

T (Temperature)

RH (Relative Humidity"""

selected_cols = ['CO(GT)', 'NOx(GT)', 'T', 'RH']

df[selected_cols].head()

          CO(GT)  NOx(GT)     T    RH
Datetime
NaT          2.6    166.0  13.6  48.9
NaT          2.0    103.0  13.3  47.7
NaT          2.2    131.0  11.9  54.0
NaT          2.2    172.0  11.0  60.0
NaT          1.6    131.0  11.2  59.6

In [ ]:
# Identify Missing Values
"""Dataset uses -200 as missing value placeholder"""
# Replace -200 with NaN
df.replace(-200, np.nan, inplace=True)

# Counting missing values
df[selected_cols].isna().sum()

CO(GT)     1797
NOx(GT)    1753
T           480
RH          480
dtype: int64

In [ ]:
# Handling te Missing Values
"""Strategy that is used:

Interpolation for CO(GT) and NOx(GT) → because they are time series sensor data

Mean filling for Temperature and Humidity"""
# Interpolation for pollutant data
df['CO(GT)'] = df['CO(GT)'].interpolate()
df['NOx(GT)'] = df['NOx(GT)'].interpolate()

# Filling temperature and humidity with mean
df['T'].fillna(df['T'].mean(), inplace=True)
df['RH'].fillna(df['RH'].mean(), inplace=True)

# Verifying missing values again
df[selected_cols].isna().sum()

/tmp/ipykernel_164/3880665858.py:12: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['T'].fillna(df['T'].mean(), inplace=True)
/tmp/ipykernel_164/3880665858.py:13: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['RH'].fillna(df['RH'].mean(), inplace=True)

CO(GT)     0
NOx(GT)    0
T          0
RH         0
dtype: int64

In [ ]:
# Descriptive Statistics
df[selected_cols].describe()

"""Explanation: -

Mean: Average sensor reading

Std: Indicates variability in pollutant levels

Min/Max: Shows extreme pollution or weather conditions"""

'Explanation: -\n\nMean: Average sensor reading\n\nStd: Indicates variability in pollutant levels\n\nMin/Max: Shows extreme pollution or weather conditions'

In [ ]:
# Checking and Converting the Data Types
df[selected_cols].dtypes

CO(GT)     float64
NOx(GT)    float64
T          float64
RH         float64
dtype: object

In [ ]:
df[selected_cols] = df[selected_cols].astype(float)

In [ ]:
# Combining Date and Time into a single datetime column
df['Datetime'] = pd.to_datetime(df['Date'] + ' ' + df['Time'], errors='coerce')

# Removing the rows where datetime conversion failed
df = df.dropna(subset=['Datetime'])

# Setting datetime as index
df.set_index('Datetime', inplace=True)

# Sortting the index
df = df.sort_index()

df.head()

Empty DataFrame
Columns: [Date, Time, CO(GT), PT08.S1(CO), NMHC(GT), C6H6(GT), PT08.S2(NMHC), NOx(GT), PT08.S3(NOx), NO2(GT), PT08.S4(NO2), PT08.S5(O3), T, RH, AH, Unnamed: 15, Unnamed: 16]
Index: []

In [ ]:
# Resampling the Data to Daily Average - Hours to Daily

daily_data = df[selected_cols].resample('D').mean()

daily_data.head()

Empty DataFrame
Columns: [CO(GT), NOx(GT), T, RH]
Index: []

In [ ]:
# Checking number of observations
print("Total daily rows:", len(daily_data))
print("CO(GT) non-null values:", daily_data['CO(GT)'].count())

Total daily rows: 0
CO(GT) non-null values: 0

In [ ]:
# Interpolate Missing Values
# Fill missing values using interpolation
daily_data['CO(GT)'] = daily_data['CO(GT)'].interpolate()

# Removing any remaining NaN
co_series = daily_data['CO(GT)'].dropna()

print("Final observations used:", len(co_series))

Final observations used: 0

In [ ]:
# Plot Decomposition
decomposition.plot()
plt.show()

NameError: name 'decomposition' is not defined

In [ ]:
# Normalization (MinMaxScaler)
Normalize CO(GT)
scaler = MinMaxScaler()

df['CO_normalized'] = scaler.fit_transform(df[['CO(GT)']])

df[['CO(GT)', 'CO_normalized']].head()

SyntaxError: invalid syntax (3566280079.py, line 2)

In [ ]:
# Standardization (StandardScaler)
Standardize Temperature and Humidity
std_scaler = StandardScaler()

df[['T_std','RH_std']] = std_scaler.fit_transform(df[['T','RH']])

df[['T','T_std','RH','RH_std']].head()

SyntaxError: invalid syntax (1057352948.py, line 2)

In [ ]:
# Visualization with Custom Ticks
Plot normalized pollutant.
plt.figure(figsize=(12,6))

plt.plot(df.index, df['CO_normalized'], label='Normalized CO(GT)')

ax = plt.gca()

# Major ticks = Year
ax.xaxis.set_major_locator(mdates.YearLocator())

# Minor ticks = Month
ax.xaxis.set_minor_locator(mdates.MonthLocator())

plt.xlabel("Time")
plt.ylabel("Normalized CO Concentration")
plt.title("Normalized CO(GT) Over Time")
plt.legend()

plt.show()

SyntaxError: invalid syntax (737192807.py, line 2)

In [ ]:
# Interpretation
"""Trend:-
CO levels show fluctuations over time which may relate to traffic or seasonal effects.

Seasonality:-
Possible weekly or monthly pollution patterns.

Residual:-
Random noise due to sensor variation or sudden environmental changes"""

'Trend:-\nCO levels show fluctuations over time which may relate to traffic or seasonal effects.\n\nSeasonality:-\nPossible weekly or monthly pollution patterns.\n\nResidual:-\nRandom noise due to sensor variation or sudden environmental changes'